vim.opt.autowrite = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.wrap = false
vim.opt.signcolumn = "yes"
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smarttab = true
vim.opt.smartindent = true
vim.opt.scrolloff = 6
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.incsearch = true
vim.opt.hlsearch = false
vim.opt.undofile = true
vim.opt.backup = false
vim.opt.writebackup = false
vim.opt.swapfile = false
vim.opt.mouse = "a"
vim.opt.guicursor = ""
vim.opt.showmode = false
vim.opt.showcmd = false
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.laststatus = 3
vim.opt.clipboard = "unnamedplus"
vim.opt.cmdheight = 1
vim.opt.wildmode = ""
vim.opt.completeopt = { "menu", "menuone", "noselect" }
vim.opt.conceallevel = 3
vim.opt.confirm = true
vim.opt.grepprg = "rg --vimgrep"
vim.opt.iskeyword:remove("_")
vim.opt.hidden = false

vim.g.mapleader = " "
vim.g.netrw_banner = 0
